export const REMINDER_PICKER_COPY = {
	schedule: {
		title: 'Schedule',
		dialogLabel: 'Schedule reminder',
		closeLabel: 'Close schedule',
		done: 'Done',
		current: 'Scheduled',
		quickOptions: 'Quick options',
		custom: 'Custom',
		date: 'Date',
		time: 'Time',
		addDate: 'Add date',
		addTime: 'Add time',
		invalidDate: 'Enter a valid date',
		optional: 'Optional',
		remove: 'Remove schedule',
	},
	project: {
		title: 'Project',
		done: 'Done',
		dialogLabel: 'Select project',
		closeLabel: 'Close project selection',
		listLabel: 'Project selection',
	},
	repeat: {
		title: 'Repeat',
		dialogLabel: 'Repeat reminder',
		closeLabel: 'Close repeat',
		done: 'Done',
		current: 'Repeats',
		frequency: 'Frequency',
		interval: 'Interval',
		days: 'Days',
		monthDay: 'Month day',
		every: 'Every',
		dayOfMonth: 'Day of month',
		calendarDate: 'Calendar date',
		time: 'Time',
		reminderTime: 'Reminder time',
		remove: 'Remove repeat',
	},
	editor: {
		date: 'Date',
		defaultProject: 'Inbox',
		priority: 'Priority',
		repeat: 'Repeat',
		recurrenceLabel: 'Recurrence',
	},
} as const;
