import { describe, expect, it } from 'vitest';
import { constantTimeEqual, createPkcePair, randomBase64Url, randomHex } from './pkce';

describe('Cloudflare OAuth PKCE helpers', () => {
	it('creates an S256 verifier and challenge without base64 padding', async () => {
		const pair = await createPkcePair();
		const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(pair.verifier));
		const expected = btoa(String.fromCharCode(...new Uint8Array(digest)))
			.replace(/\+/g, '-')
			.replace(/\//g, '_')
			.replace(/=+$/g, '');

		expect(pair.verifier).toMatch(/^[A-Za-z0-9_-]{80,}$/);
		expect(pair.challenge).toBe(expected);
		expect(pair.challenge).not.toContain('=');
	});

	it('uses cryptographically generated bytes for state and deployment IDs', () => {
		const firstState = randomBase64Url(32);
		const secondState = randomBase64Url(32);
		expect(firstState).toMatch(/^[A-Za-z0-9_-]{43}$/);
		expect(secondState).not.toBe(firstState);
		expect(randomHex(8)).toMatch(/^[a-f0-9]{16}$/);
	});

	it('compares state values without returning early for different lengths', () => {
		expect(constantTimeEqual('matching-state', 'matching-state')).toBe(true);
		expect(constantTimeEqual('matching-state', 'different-state')).toBe(false);
		expect(constantTimeEqual('short', 'much-longer')).toBe(false);
	});
});
