import { CRATE_PLUGIN_PROTOCOL } from '@/protocol';
import { READING_SHORTCUT_CONTRACT as contract } from '@/reading/shortcut';
import release from '../../server-release.json';
import { PWA_ASSET_VERSION } from '../pwa-version';
import { runReadingSavePage, type ReadingSaveConfig } from './save-client';

const pageHeaders = (type: string) => ({ 'Content-Type': type, 'Cache-Control': 'no-store', 'Referrer-Policy': 'no-referrer', 'X-Content-Type-Options': 'nosniff',
  'Content-Security-Policy': "default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; img-src 'self' https://crate.kaanbiryol.com; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'" });
interface PageOptions { supportOnly?: boolean; scriptUrl?: string; serverFingerprint?: string }

export function readingSavePage({ supportOnly = false, scriptUrl = '/notifications/save-reading.js' }: PageOptions = {}): Response {
  const logo = supportOnly ? 'https://crate.kaanbiryol.com/assets/logo.png' : '/notifications/crate-mark-256.png';
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><meta name="referrer" content="no-referrer"><title>Save to Crate</title><style>
  :root{font-family:system-ui,sans-serif;color:#18181b;background:#f7f7f8;color-scheme:light dark;--surface:#fff;--muted:#71717a;--line:#e4e4e7;--accent:#6d28d9}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:24px;padding-top:max(24px,env(safe-area-inset-top));padding-bottom:max(24px,env(safe-area-inset-bottom))}main{width:100%;max-width:420px;text-align:center;padding:24px 0}img{width:64px;height:64px;object-fit:contain;margin-bottom:24px}h1{font-size:28px;letter-spacing:-.03em;margin:0 0 12px;text-wrap:balance}h2{font-size:18px;margin:0 0 8px}p{line-height:1.6;color:var(--muted);margin:12px 0}.actions{display:grid;gap:10px;margin:20px 0}button,a.action{display:block;width:100%;border:1px solid transparent;border-radius:14px;background:var(--accent);color:#fff;padding:14px 18px;font:inherit;text-decoration:none;min-height:48px;cursor:pointer}button.secondary,a.secondary{color:inherit;border-color:var(--line);background:var(--surface)}button:disabled{opacity:.6;cursor:default}#support,#update{border-top:1px solid var(--line);padding-top:20px;margin-top:24px}.small{font-size:13px}details{text-align:left;margin-top:16px}summary{padding:10px 0;cursor:pointer;min-height:44px}label{display:block;font-size:13px;color:var(--muted);margin:8px 0}textarea{width:100%;min-height:240px;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--surface);color:inherit;font:13px/1.5 ui-monospace,monospace;resize:vertical}.spinner{height:24px;width:24px;border:2px solid var(--line);border-top-color:var(--accent);border-radius:50%;margin:20px auto;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.spinner{animation:none}}@media(prefers-color-scheme:dark){:root{color:#f4f4f5;background:#18181b;--surface:#27272a;--muted:#a1a1aa;--line:#3f3f46;--accent:#7c3aed}}:focus-visible{outline:3px solid #a78bfa;outline-offset:4px}
  </style></head><body><main><img src="${logo}" alt="Crate"><div class="spinner" id="progress" aria-hidden="true"></div><h1 id="title">Saving to Crate…</h1><p id="message" role="status" aria-live="polite">Keeping this link for later.</p>
  <div class="actions"><button id="retry" hidden>Retry save</button><button id="reload" hidden>Reload save page</button><a class="action" id="open" href="/notifications?section=reading" hidden>Open Reading</a></div><p id="close-hint" class="small">Wait for confirmation before closing this page.</p>
  <section id="update" aria-labelledby="update-title" hidden><h2 id="update-title">Update your shortcut</h2><p id="update-message"></p><div class="actions"><a class="action secondary" id="download" href="${contract.downloadUrl}" target="_blank" rel="noopener noreferrer">Download shortcut</a><a class="action secondary" id="reconnect" href="/notifications?section=reading&amp;setup=shortcut">Open shortcut setup</a></div><p class="small">Install in Shortcuts, then create a pairing code in the enrolled Crate app’s Reading settings. Updates are installed by you.</p></section>
  <section id="support" aria-label="Save diagnostics" hidden><div class="actions"><button class="secondary" id="copy">Copy diagnostics</button><a class="action secondary" id="issue" href="${contract.issuesUrl}" target="_blank" rel="noopener noreferrer">Report on GitHub</a></div><p id="copy-status" role="status" class="small"></p><details id="diagnostic-details"><summary>View diagnostics</summary><label for="diagnostics">Diagnostics</label><textarea id="diagnostics" readonly spellcheck="false" autocapitalize="none"></textarea></details><p class="small">Article URLs, pairing codes, and access credentials are excluded. You can review the issue before submitting it.</p></section>
  <noscript><p>This save has not been confirmed. Enable JavaScript or share the article again.</p></noscript></main><script src="${scriptUrl}" defer></script></body></html>`, { headers: pageHeaders('text/html; charset=utf-8') });
}

export function readingSaveScript({ supportOnly = false, serverFingerprint }: PageOptions = {}): Response {
  const config: ReadingSaveConfig = { wireProtocol: supportOnly ? null : CRATE_PLUGIN_PROTOCOL.current,
    serverRevision: supportOnly ? null : release.revision,
    serverFingerprint: !supportOnly && serverFingerprint && /^[a-f0-9]{64}$/.test(serverFingerprint) ? serverFingerprint : null,
    pwaVersion: supportOnly ? null : PWA_ASSET_VERSION,
    shortcutContract: contract.version, shortcutRevision: contract.revision, downloadUrl: contract.downloadUrl, issuesUrl: contract.issuesUrl, supportOnly };
  return new Response(`(${runReadingSavePage.toString()})(${JSON.stringify(config)});`, { headers: pageHeaders('application/javascript') });
}
