import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const buildVersion = Date.now().toString(36);

function escapeForTemplateLiteral(value) {
	return value
		.replace(/\\/g, '\\\\')
		.replace(/`/g, '\\`')
		.replace(/\$\{/g, '\\${');
}

function writePwaVersionModule() {
	const output = `// Auto-generated by scripts/build-worker.mjs - do not edit
export const PWA_ASSET_VERSION = '${buildVersion}';
`;

	const outPath = resolve(root, 'src/cloudflare/worker/pwa-version.gen.ts');
	writeFileSync(outPath, output, 'utf-8');
}

async function buildWorkerBundle() {
	const result = await build({
		entryPoints: [resolve(root, 'src/cloudflare/worker/index.ts')],
		bundle: true,
		format: 'esm',
		platform: 'neutral',
		target: 'esnext',
		write: false,
		minify: false,
		mainFields: ['module', 'main'],
		conditions: ['worker', 'browser', 'import'],
	});

	const code = result.outputFiles[0].text;
	const escaped = escapeForTemplateLiteral(code);
	const output = `// Auto-generated by scripts/build-worker.mjs - do not edit
export function getWorkerScript(): string {
	return \`${escaped}\`;
}
`;

	const outPath = resolve(root, 'src/cloudflare/worker-bundle.gen.ts');
	writeFileSync(outPath, output, 'utf-8');
	console.log('Worker bundle written to src/cloudflare/worker-bundle.gen.ts');
}

async function buildPwaClientBundle() {
	const result = await build({
		entryPoints: [resolve(root, 'src/cloudflare/worker/pwa-client.tsx')],
		bundle: true,
		format: 'esm',
		platform: 'browser',
		target: 'es2020',
		write: false,
		minify: false,
		mainFields: ['browser', 'module', 'main'],
		conditions: ['browser', 'import'],
	});

	const code = result.outputFiles[0].text;
	const escaped = escapeForTemplateLiteral(code);
	const output = `// Auto-generated by scripts/build-worker.mjs - do not edit
export const PWA_CLIENT_JS = \`${escaped}\`;
`;

	const outPath = resolve(root, 'src/cloudflare/worker/pwa-client-bundle.gen.ts');
	writeFileSync(outPath, output, 'utf-8');
	console.log('PWA client bundle written to src/cloudflare/worker/pwa-client-bundle.gen.ts');
}

writePwaVersionModule();
await buildPwaClientBundle();
await buildWorkerBundle();
