import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const result = await build({
	entryPoints: [resolve(root, 'src/cloudflare/worker/index.ts')],
	bundle: true,
	format: 'esm',
	platform: 'neutral',
	target: 'esnext',
	write: false,
	minify: false,
	mainFields: ['module', 'main'],
	conditions: ['worker', 'browser', 'import'],
});

const code = result.outputFiles[0].text;

// Escape backticks and ${} in the bundled code so it can live inside a template literal
const escaped = code
	.replace(/\\/g, '\\\\')
	.replace(/`/g, '\\`')
	.replace(/\$\{/g, '\\${');

const output = `// Auto-generated by scripts/build-worker.mjs - do not edit
export function getWorkerScript(): string {
	return \`${escaped}\`;
}
`;

const outPath = resolve(root, 'src/cloudflare/worker-bundle.gen.ts');
writeFileSync(outPath, output, 'utf-8');
console.log('Worker bundle written to src/cloudflare/worker-bundle.gen.ts');
