export {
	handleBatchDelete,
	handleBatchDownload,
	handleBatchUpload,
	handleCheckChanges,
	handleDelete,
	handleDownload,
	handleGetChanges,
	handleGetFileMetadata,
	handleGetManifest,
	handleGetSettings,
	handleHealth,
	handlePutSettings,
	handleUpload,
} from '../sync-handlers';
